### ISSUE TITLE
Restrict the included code blocks to a given number of lines

### ISSUE THREAD

**Issue by Becheler** [dineshsonachalam/markdown-autodocs#10]
I came to your repository because my previous attempt to use another repo (https://github.com/tokusumi/markdown-embed-code)  failed. Markdown autodocs worked perfectly and I feel blessed 👍🏽 

However, I liked this feature on this other repo: the fact you could possibly refer to specific lines to be included using ```[begin-end]``` syntax:
```  
\```python:tests/src/sample.py [4-5]
  
\```
```
Can we hope to see this feature developed any time soon?

**Comment by dineshsonachalam** [comment]
Hi @Becheler,

This feature is already available in the markdown-autodocs for code-block.

I missed adding an optional parameter called lines for the code-block in markdown-autodocs documentation.

**lines (optional):** a range with lines of code which will then be replaced with code from the file. The line range should be defined as: "lines=startLine-EndLine" (for example: "lines=22-44").

Please take a look at the below example.

## Before using markdown-autodocs:
![image](https://user-images.githubusercontent.com/12673979/148172005-5472905e-9646-4642-bfd1-7f93f3d4d7f9.png)

## After using markdown-autodocs:
![image](https://user-images.githubusercontent.com/12673979/148172059-634504bb-255a-4ec0-b2e2-ccd9304c7de5.png)

Please feel to reach out to me with any questions.

**Comment by Becheler** [comment]
Wonderful! 
Thank you so much for your prompt answer! Have a wonderful weekend!
