### ISSUE TITLE
Is it possible to give a directory as `output_file_paths`?

### ISSUE THREAD

**Issue by anupama-pathirage** [dineshsonachalam/markdown-autodocs#12]
I need to inject code snippets to many .md files in my project. 

So instead of mentioning each .md file one by one as follows, is there any way to give the full directory?

Currently I am achieving it as https://github.com/anupama-pathirage/learning_ballerina/blob/master/.github/workflows/gh-pages.yml#L20

```yaml
with:
          output_file_paths: '[./src/simple_basic_types/boolean.md,./src/simple_basic_types/decimal.md,./src/simple_basic_types/float.md]'
```

So my question is can't we have something like below?

```yaml
with:
          output_file_paths: '[./src/simple_basic_types/*]'
```

Btw, thanks for great project

**Comment by dineshsonachalam** [comment]
Thanks for the suggestion @anupama-pathirage. I will raise an MR tomorrow to support this feature.

**Comment by dineshsonachalam** [comment]
Hi, @anupama-pathirage,

I added support to give a directory as output_file_paths. You just need to add this step in your gh-pages.yml.

```
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          output_file_paths: '[./src/simple_basic_types/*]' 
```
Reference: https://github.com/dineshsonachalam/learning_ballerina/blob/master/.github/workflows/gh-pages.yml

**Before Markdown-autodocs:** https://github.com/dineshsonachalam/learning_ballerina/commit/b90ff97307be0faef704e293ac91db5db06d179b
**After Mardkdown-autodocs:** https://github.com/dineshsonachalam/learning_ballerina/commit/0ac4b292bed965fc10273dc46d7871aa452ffdb8

Feel free to reach out if you have any questions.

Thanks,
Dinesh

**Comment by anupama-pathirage** [comment]
Great. It  worked well. Thank you.
