### ISSUE TITLE
Is your action app free?

### ISSUE THREAD

**Issue by tst32** [dineshsonachalam/markdown-autodocs#6]
![image](https://user-images.githubusercontent.com/23115742/127284903-09122b2e-9bfd-4287-b0e0-7a59d482a2d2.png)
your app is not labeled with 🆓 free tag in marketplace is it intended to be by design?

**Comment by dineshsonachalam** [comment]
This project is licensed under terms of the MIT license. It's free software. 

**Reference:** 
1. Markdown-autodocs License: https://github.com/dineshsonachalam/markdown-autodocs/blob/master/LICENSE
2. MIT license: https://tldrlegal.com/license/mit-license
