### ISSUE TITLE
Could be included other markdown file in README.md  this way

### ISSUE THREAD

**Issue by tst32** [dineshsonachalam/markdown-autodocs#7]
![image](https://user-images.githubusercontent.com/23115742/127292534-ed909fac-c248-4755-bf71-c60333daefc7.png)

i have added action in my python-app.yml  the build passed. all works fine. thanks! but i m :looking: for way to include md file in my README.md do you know the answer?
cheer

**Comment by dineshsonachalam** [comment]
Hi @tst32,

Currently, this Github Action doesn't support ways to include the markdown(.md) files in README.md. I will add support for this functionality end of this week.  Please feel free to ask any questions or open a new feature request.

![Feature_Request](https://user-images.githubusercontent.com/12673979/127542563-444a3563-96e2-47e1-9fde-8a0acc50abf9.png)
